### ISSUE TITLE
Add brief user guide to `docs/`

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/de_sim#46]
This should include at least one example.

Ideally, this would also include a tutorial and/or example as a Jupyter notebook which can be hosted at https://sandbox.karrlab.org

**Comment by jonrkarr** [comment]
I see there are some examples in `de_sim.examples` and Jupyter notebooks. The Jupyter notebooks should use a simpler example that doesn't rely on `wc_sim`. Also, there is a missing file which is needed to execute the notebooks (`Users/arthur_at_sinai/gitOnMyLaptopLocal/wc_sim/wc_sim/multialgorithm/dataframe_file.h5`). I added a unit test to verify that the Jupyter notebooks execute.

**Comment by artgoldberg** [comment]
Done.
