### ISSUE TITLE
Dead links in tutorial 1

### ISSUE THREAD

**Issue by gonsie** [KarrLab/de_sim#57]
This issue is related to openjournals/joss-reviews#2685

Tutorial `1. DE-Sim tutorial.ipynb` has dead links. It references an “Advanced DE Sim notebook” which does not exist.

**Comment by artgoldberg** [comment]
Fixed in repo. https://sandbox.karrlab.org/tree/de_sim must be re-deployed.

**Comment by artgoldberg** [comment]
Fixed completely.
